spring:
  application:
    name: "b3.agregadorInvestimentos"
  datasource:
    url: jdbc:postgresql://localhost:5446/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver